/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  Equipment,
  Intervention,
  SparePart,
  Vendor,
  MaintenanceContract,
  BudgetYear,
  ComplianceCheck,
  Workshop,
  PurchaseRequest
} from "./types";

export const WORKSHOPS: Workshop[] = [
  "Service Rapide",
  "Atelier Mécanique",
  "Atelier Diagnostic",
  "Carrosserie",
  "Lavage",
  "Réception Après-Vente",
  "Magasin Pièces de Rechange",
  "Maintenance Bâtiment"
];

export const INITIAL_EQUIPMENTS: Equipment[] = [
  // === NEW EQUIPMENTS EXTRACTED FROM CHERY EXCEL ===

  // --- Zone: Service Rapide ---
  {
    code: "EQ-SR-03",
    name: "Poignée de distribution d'huile",
    workshop: "Service Rapide",
    status: "Hors Service",
    purchaseDate: "2023-01-10",
    warrantyEnd: "2025-01-10",
    purchasePrice: 350,
    location: "Poste Distribution Fluides",
    serialNumber: "GT-OIL-03",
    critical: true,
    mtbfTargetHours: 1000,
    mttrTargetHours: 2
  },
  {
    code: "EQ-SR-04",
    name: "Poignée de distribution d'huile",
    workshop: "Service Rapide",
    status: "Opérationnel",
    purchaseDate: "2023-01-10",
    warrantyEnd: "2025-01-10",
    purchasePrice: 350,
    location: "Poste Distribution Fluides",
    serialNumber: "GT-OIL-04",
    critical: true,
    mtbfTargetHours: 1000,
    mttrTargetHours: 2
  },
  {
    code: "EQ-SR-05",
    name: "Pont élévateur (Ravaglioli) - 1/4",
    workshop: "Service Rapide",
    status: "Dégradé",
    purchaseDate: "2022-04-15",
    warrantyEnd: "2024-04-15",
    purchasePrice: 13800,
    location: "Zone Service Rapide - Postes 1-4",
    serialNumber: "RAV-SR-01",
    critical: true,
    mtbfTargetHours: 1200,
    mttrTargetHours: 4
  },
  {
    code: "EQ-SR-06",
    name: "Pont élévateur (Ravaglioli) - 2/4",
    workshop: "Service Rapide",
    status: "Dégradé",
    purchaseDate: "2022-04-15",
    warrantyEnd: "2024-04-15",
    purchasePrice: 13800,
    location: "Zone Service Rapide - Postes 1-4",
    serialNumber: "RAV-SR-02",
    critical: true,
    mtbfTargetHours: 1200,
    mttrTargetHours: 4
  },
  {
    code: "EQ-SR-07",
    name: "Pont élévateur (Ravaglioli) - 3/4",
    workshop: "Service Rapide",
    status: "Dégradé",
    purchaseDate: "2022-04-15",
    warrantyEnd: "2024-04-15",
    purchasePrice: 13800,
    location: "Zone Service Rapide - Postes 1-4",
    serialNumber: "RAV-SR-03",
    critical: true,
    mtbfTargetHours: 1200,
    mttrTargetHours: 4
  },
  {
    code: "EQ-SR-08",
    name: "Pont élévateur (Ravaglioli) - 4/4",
    workshop: "Service Rapide",
    status: "Dégradé",
    purchaseDate: "2022-04-15",
    warrantyEnd: "2024-04-15",
    purchasePrice: 13800,
    location: "Zone Service Rapide - Postes 1-4",
    serialNumber: "RAV-SR-04",
    critical: true,
    mtbfTargetHours: 1200,
    mttrTargetHours: 4
  },
  {
    code: "EQ-SR-09",
    name: "Flexible air comprimé",
    workshop: "Service Rapide",
    status: "Dégradé",
    purchaseDate: "2024-02-10",
    warrantyEnd: "2025-02-10",
    purchasePrice: 120,
    location: "Postes de travail Service Rapide",
    serialNumber: "FLX-SR-01",
    critical: false,
    mtbfTargetHours: 800,
    mttrTargetHours: 1
  },
  {
    code: "EQ-SR-10",
    name: "Récupérateur d'huile (APAC B01F) - 1/4",
    workshop: "Service Rapide",
    status: "Dégradé",
    purchaseDate: "2021-08-11",
    warrantyEnd: "2023-08-11",
    purchasePrice: 1100,
    location: "Zone Huiles Usagées",
    serialNumber: "APAC-B01F-01",
    critical: true,
    mtbfTargetHours: 900,
    mttrTargetHours: 2
  },
  {
    code: "EQ-SR-11",
    name: "Récupérateur d'huile (APAC B01F) - 2/4",
    workshop: "Service Rapide",
    status: "Dégradé",
    purchaseDate: "2021-08-11",
    warrantyEnd: "2023-08-11",
    purchasePrice: 1100,
    location: "Zone Huiles Usagées",
    serialNumber: "APAC-B01F-02",
    critical: true,
    mtbfTargetHours: 900,
    mttrTargetHours: 2
  },
  {
    code: "EQ-SR-12",
    name: "Récupérateur d'huile (APAC B01F) - 3/4",
    workshop: "Service Rapide",
    status: "Dégradé",
    purchaseDate: "2021-08-11",
    warrantyEnd: "2023-08-11",
    purchasePrice: 1100,
    location: "Zone Huiles Usagées",
    serialNumber: "APAC-B01F-03",
    critical: true,
    mtbfTargetHours: 900,
    mttrTargetHours: 2
  },
  {
    code: "EQ-SR-13",
    name: "Récupérateur d'huile (APAC B01F) - 4/4",
    workshop: "Service Rapide",
    status: "Dégradé",
    purchaseDate: "2021-08-11",
    warrantyEnd: "2023-08-11",
    purchasePrice: 1100,
    location: "Zone Huiles Usagées",
    serialNumber: "APAC-B01F-04",
    critical: true,
    mtbfTargetHours: 900,
    mttrTargetHours: 2
  },
  {
    code: "EQ-SR-14",
    name: "Clé à choc (ACEM)",
    workshop: "Service Rapide",
    status: "Hors Service",
    purchaseDate: "2023-06-20",
    warrantyEnd: "2024-06-20",
    purchasePrice: 450,
    location: "Armoire outillage Service Rapide",
    serialNumber: "ACM-SR-CHOC-01",
    critical: true,
    mtbfTargetHours: 800,
    mttrTargetHours: 2
  },
  {
    code: "EQ-SR-15",
    name: "Cale plastique (gomme) 1/2",
    workshop: "Service Rapide",
    status: "Hors Service",
    purchaseDate: "2024-01-15",
    warrantyEnd: "2025-01-15",
    purchasePrice: 50,
    location: "Ponts de travail SR",
    serialNumber: "CAL-SR-01",
    critical: false,
    mtbfTargetHours: 500,
    mttrTargetHours: 1
  },
  {
    code: "EQ-SR-16",
    name: "Cale plastique (gomme) 2/2",
    workshop: "Service Rapide",
    status: "Hors Service",
    purchaseDate: "2024-01-15",
    warrantyEnd: "2025-01-15",
    purchasePrice: 50,
    location: "Ponts de travail SR",
    serialNumber: "CAL-SR-02",
    critical: false,
    mtbfTargetHours: 500,
    mttrTargetHours: 1
  },
  {
    code: "EQ-SR-17",
    name: "Miroir d'inspection 1/2",
    workshop: "Service Rapide",
    status: "Dégradé",
    purchaseDate: "2023-09-01",
    warrantyEnd: "2024-09-01",
    purchasePrice: 120,
    location: "Baies de travail SR",
    serialNumber: "MIR-SR-01",
    critical: false,
    mtbfTargetHours: 1000,
    mttrTargetHours: 1
  },
  {
    code: "EQ-SR-18",
    name: "Miroir d'inspection 2/2",
    workshop: "Service Rapide",
    status: "Dégradé",
    purchaseDate: "2023-09-01",
    warrantyEnd: "2024-09-01",
    purchasePrice: 120,
    location: "Baies de travail SR",
    serialNumber: "MIR-SR-02",
    critical: false,
    mtbfTargetHours: 1000,
    mttrTargetHours: 1
  },

  // --- Zone: Atelier (Atelier Mécanique) ---
  {
    code: "EQ-AM-03",
    name: "Machine d'équilibrage de roue",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2022-10-15",
    warrantyEnd: "2024-10-15",
    purchasePrice: 6500,
    location: "Zone Pneumatique Atelier",
    serialNumber: "RAV-EQ-981",
    critical: true,
    mtbfTargetHours: 1000,
    mttrTargetHours: 3
  },
  {
    code: "EQ-AM-04",
    name: "Aspirateur industriel d'atelier",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2024-03-12",
    warrantyEnd: "2025-03-12",
    purchasePrice: 850,
    location: "Aire de nettoyage",
    serialNumber: "ASP-AM-04",
    critical: false,
    mtbfTargetHours: 700,
    mttrTargetHours: 2
  },
  {
    code: "EQ-AM-05",
    name: "Démonte pneu (Ravaglioli)",
    workshop: "Atelier Mécanique",
    status: "Dégradé",
    purchaseDate: "2022-10-15",
    warrantyEnd: "2024-10-15",
    purchasePrice: 5800,
    location: "Zone Pneumatique Atelier",
    serialNumber: "RAV-DP-982",
    critical: true,
    mtbfTargetHours: 800,
    mttrTargetHours: 3
  },
  {
    code: "EQ-AM-06",
    name: "Testeur de freinage et suspension",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2023-04-18",
    warrantyEnd: "2025-04-18",
    purchasePrice: 18500,
    location: "Baie d'accueil & test",
    serialNumber: "RAV-FR-504",
    critical: true,
    mtbfTargetHours: 1100,
    mttrTargetHours: 4
  },
  {
    code: "EQ-AM-07",
    name: "Cric girafe",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2023-11-22",
    warrantyEnd: "2024-11-22",
    purchasePrice: 1400,
    location: "Zone outillage lourd",
    serialNumber: "MEG-GIR-07",
    critical: true,
    mtbfTargetHours: 1000,
    mttrTargetHours: 2
  },
  {
    code: "EQ-AM-08",
    name: "Gonfleur de pneu mural",
    workshop: "Atelier Mécanique",
    status: "Hors Service",
    purchaseDate: "2023-01-20",
    warrantyEnd: "2024-01-20",
    purchasePrice: 420,
    location: "Zone Pneumatique Atelier",
    serialNumber: "GONF-AM-01",
    critical: false,
    mtbfTargetHours: 600,
    mttrTargetHours: 1
  },
  {
    code: "EQ-AM-09",
    name: "Enrouleur d'air comprimé (Lot de 7)",
    workshop: "Atelier Mécanique",
    status: "Dégradé",
    purchaseDate: "2022-06-14",
    warrantyEnd: "2024-06-14",
    purchasePrice: 2100,
    location: "Poteaux d'atelier",
    serialNumber: "ENR-AM-7S",
    critical: false,
    mtbfTargetHours: 800,
    mttrTargetHours: 2
  },
  {
    code: "EQ-AM-11",
    name: "Pont géométrie + appareil géométrie",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2024-05-10",
    warrantyEnd: "2026-05-10",
    purchasePrice: 31000,
    location: "Zone alignement 3D",
    serialNumber: "RAV-GEO-3D",
    critical: true,
    mtbfTargetHours: 1500,
    mttrTargetHours: 5
  },
  {
    code: "EQ-AM-12",
    name: "Machine de rinçage boîte automatique",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2024-11-15",
    warrantyEnd: "2025-11-15",
    purchasePrice: 7800,
    location: "Poste mécanique Expert",
    serialNumber: "TE-ATF-12",
    critical: true,
    mtbfTargetHours: 1200,
    mttrTargetHours: 3
  },
  {
    code: "EQ-AM-13",
    name: "Pont élévateur (Ravaglioli) - 1/5",
    workshop: "Atelier Mécanique",
    status: "Dégradé",
    purchaseDate: "2022-09-12",
    warrantyEnd: "2024-09-12",
    purchasePrice: 14500,
    location: "Postes Mécanique 1-5",
    serialNumber: "RAV-AM-01",
    critical: true,
    mtbfTargetHours: 1100,
    mttrTargetHours: 4
  },
  {
    code: "EQ-AM-14",
    name: "Pont élévateur (Ravaglioli) - 2/5",
    workshop: "Atelier Mécanique",
    status: "Dégradé",
    purchaseDate: "2022-09-12",
    warrantyEnd: "2024-09-12",
    purchasePrice: 14500,
    location: "Postes Mécanique 1-5",
    serialNumber: "RAV-AM-02",
    critical: true,
    mtbfTargetHours: 1100,
    mttrTargetHours: 4
  },
  {
    code: "EQ-AM-15",
    name: "Pont élévateur (Ravaglioli) - 3/5",
    workshop: "Atelier Mécanique",
    status: "Dégradé",
    purchaseDate: "2022-09-12",
    warrantyEnd: "2024-09-12",
    purchasePrice: 14500,
    location: "Postes Mécanique 1-5",
    serialNumber: "RAV-AM-03",
    critical: true,
    mtbfTargetHours: 1100,
    mttrTargetHours: 4
  },
  {
    code: "EQ-AM-16",
    name: "Pont élévateur (Ravaglioli) - 4/5",
    workshop: "Atelier Mécanique",
    status: "Dégradé",
    purchaseDate: "2022-09-12",
    warrantyEnd: "2024-09-12",
    purchasePrice: 14500,
    location: "Postes Mécanique 1-5",
    serialNumber: "RAV-AM-04",
    critical: true,
    mtbfTargetHours: 1100,
    mttrTargetHours: 4
  },
  {
    code: "EQ-AM-17",
    name: "Pont élévateur (Ravaglioli) - 5/5",
    workshop: "Atelier Mécanique",
    status: "Dégradé",
    purchaseDate: "2022-09-12",
    warrantyEnd: "2024-09-12",
    purchasePrice: 14500,
    location: "Postes Mécanique 1-5",
    serialNumber: "RAV-AM-05",
    critical: true,
    mtbfTargetHours: 1100,
    mttrTargetHours: 4
  },
  {
    code: "EQ-AM-18",
    name: "Étau d'établi Expert - 1/2",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2023-02-10",
    warrantyEnd: "2025-02-10",
    purchasePrice: 280,
    location: "Établi Central",
    serialNumber: "EXP-ET-01",
    critical: true,
    mtbfTargetHours: 2000,
    mttrTargetHours: 1
  },
  {
    code: "EQ-AM-19",
    name: "Étau d'établi Expert - 2/2",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2023-02-10",
    warrantyEnd: "2025-02-10",
    purchasePrice: 280,
    location: "Établi Central",
    serialNumber: "EXP-ET-02",
    critical: true,
    mtbfTargetHours: 2000,
    mttrTargetHours: 1
  },
  {
    code: "EQ-AM-20",
    name: "Rallonge de courant électrique - 1/2",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2024-01-15",
    warrantyEnd: "2025-01-15",
    purchasePrice: 110,
    location: "Enrouleurs d'atelier",
    serialNumber: "RAL-AM-01",
    critical: false,
    mtbfTargetHours: 900,
    mttrTargetHours: 1
  },
  {
    code: "EQ-AM-21",
    name: "Rallonge de courant électrique - 2/2",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2024-01-15",
    warrantyEnd: "2025-01-15",
    purchasePrice: 110,
    location: "Enrouleurs d'atelier",
    serialNumber: "RAL-AM-02",
    critical: false,
    mtbfTargetHours: 900,
    mttrTargetHours: 1
  },
  {
    code: "EQ-AM-22",
    name: "Mélangeur",
    workshop: "Atelier Mécanique",
    status: "Dégradé",
    purchaseDate: "2023-05-15",
    warrantyEnd: "2024-05-15",
    purchasePrice: 420,
    location: "Local Produits",
    serialNumber: "MEL-AM-01",
    critical: true,
    mtbfTargetHours: 800,
    mttrTargetHours: 2
  },
  {
    code: "EQ-AM-23",
    name: "Arrache amortisseur",
    workshop: "Atelier Mécanique",
    status: "Dégradé",
    purchaseDate: "2022-03-20",
    warrantyEnd: "2023-03-20",
    purchasePrice: 980,
    location: "Poste de suspensions",
    serialNumber: "ARR-AM-01",
    critical: true,
    mtbfTargetHours: 1000,
    mttrTargetHours: 2
  },
  {
    code: "EQ-AM-24",
    name: "Pompe à huile numérique",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2024-04-10",
    warrantyEnd: "2026-04-10",
    purchasePrice: 1150,
    location: "Distribution Fluides",
    serialNumber: "PMP-NUM-01",
    critical: true,
    mtbfTargetHours: 1200,
    mttrTargetHours: 2
  },
  {
    code: "EQ-AM-25",
    name: "Presse hydraulique Mega",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2023-02-18",
    warrantyEnd: "2025-02-18",
    purchasePrice: 3200,
    location: "Zone extraction rotules",
    serialNumber: "MEG-PRS-25",
    critical: true,
    mtbfTargetHours: 1400,
    mttrTargetHours: 2
  },
  {
    code: "EQ-AM-26",
    name: "Support boîte de vitesse",
    workshop: "Atelier Mécanique",
    status: "Hors Service",
    purchaseDate: "2022-11-20",
    warrantyEnd: "2023-11-20",
    purchasePrice: 850,
    location: "Zone mécanique lourde",
    serialNumber: "SUP-BT-HS",
    critical: true,
    mtbfTargetHours: 800,
    mttrTargetHours: 2
  },
  {
    code: "EQ-AM-27",
    name: "Support boîte de vitesse",
    workshop: "Atelier Mécanique",
    status: "Dégradé",
    purchaseDate: "2022-11-20",
    warrantyEnd: "2023-11-20",
    purchasePrice: 850,
    location: "Zone mécanique lourde",
    serialNumber: "SUP-BT-OK",
    critical: true,
    mtbfTargetHours: 800,
    mttrTargetHours: 2
  },
  {
    code: "EQ-AM-28",
    name: "Support Moteur",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2023-12-05",
    warrantyEnd: "2025-12-05",
    purchasePrice: 680,
    location: "Zone mécanique lourde",
    serialNumber: "SUP-MOT-28",
    critical: true,
    mtbfTargetHours: 1500,
    mttrTargetHours: 1
  },
  {
    code: "EQ-AM-29",
    name: "Cric rouleur hydraulique Gartec",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2024-01-10",
    warrantyEnd: "2026-01-10",
    purchasePrice: 650,
    location: "Baies d'Atelier",
    serialNumber: "GT-CRIC-29",
    critical: true,
    mtbfTargetHours: 900,
    mttrTargetHours: 2
  },
  {
    code: "EQ-AM-30",
    name: "Purgeur de freins Facom - 1/2",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2023-08-22",
    warrantyEnd: "2025-08-22",
    purchasePrice: 1950,
    location: "Poste distribution fluides",
    serialNumber: "FAC-PUR-01",
    critical: true,
    mtbfTargetHours: 1200,
    mttrTargetHours: 2
  },
  {
    code: "EQ-AM-31",
    name: "Purgeur de freins Facom - 2/2",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2023-08-22",
    warrantyEnd: "2025-08-22",
    purchasePrice: 1950,
    location: "Poste distribution fluides",
    serialNumber: "FAC-PUR-02",
    critical: true,
    mtbfTargetHours: 1200,
    mttrTargetHours: 2
  },
  {
    code: "EQ-AM-32",
    name: "Tapis roulant d'atelier / chariot de visite",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2024-02-15",
    warrantyEnd: "2025-02-15",
    purchasePrice: 180,
    location: "Sous-ponts",
    serialNumber: "TAP-AM-32",
    critical: false,
    mtbfTargetHours: 1000,
    mttrTargetHours: 1
  },
  {
    code: "EQ-AM-33",
    name: "Machine de charge climatiseur (Konfort) - 1/2",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2023-05-18",
    warrantyEnd: "2025-05-18",
    purchasePrice: 8500,
    location: "Poste Climatisation",
    serialNumber: "KON-AC-01",
    critical: true,
    mtbfTargetHours: 1000,
    mttrTargetHours: 3
  },
  {
    code: "EQ-AM-34",
    name: "Machine de charge climatiseur (Konfort) - 2/2",
    workshop: "Atelier Mécanique",
    status: "Hors Service",
    purchaseDate: "2023-05-18",
    warrantyEnd: "2025-05-18",
    purchasePrice: 8500,
    location: "Poste Climatisation",
    serialNumber: "KON-AC-02",
    critical: true,
    mtbfTargetHours: 1000,
    mttrTargetHours: 3
  },
  {
    code: "EQ-AM-35",
    name: "Appareil de réglage de phares (Topauto)",
    workshop: "Atelier Mécanique",
    status: "Opérationnel",
    purchaseDate: "2024-02-05",
    warrantyEnd: "2026-02-05",
    purchasePrice: 1800,
    location: "Baie d'inspection active",
    serialNumber: "TOP-REG-35",
    critical: true,
    mtbfTargetHours: 1400,
    mttrTargetHours: 1
  },
  {
    code: "EQ-AM-36",
    name: "Servante d'atelier complète - 1/2",
    workshop: "Atelier Mécanique",
    status: "Dégradé",
    purchaseDate: "2022-05-10",
    warrantyEnd: "2024-05-10",
    purchasePrice: 1900,
    location: "Postes Mécanique",
    serialNumber: "SRV-AM-01",
    critical: true,
    mtbfTargetHours: 1500,
    mttrTargetHours: 1
  },
  {
    code: "EQ-AM-37",
    name: "Servante d'atelier complète - 2/2",
    workshop: "Atelier Mécanique",
    status: "Dégradé",
    purchaseDate: "2022-05-10",
    warrantyEnd: "2024-05-10",
    purchasePrice: 1900,
    location: "Postes Mécanique",
    serialNumber: "SRV-AM-02",
    critical: true,
    mtbfTargetHours: 1500,
    mttrTargetHours: 1
  },

  // --- Zone: Carrosserie ---
  {
    code: "EQ-CR-02",
    name: "Marbre de redressage carrosserie",
    workshop: "Carrosserie",
    status: "Dégradé",
    purchaseDate: "2021-12-10",
    warrantyEnd: "2023-12-10",
    purchasePrice: 28500,
    location: "Aire de redressage Marbre",
    serialNumber: "SPN-MARB-02",
    critical: true,
    mtbfTargetHours: 2000,
    mttrTargetHours: 5
  },
  {
    code: "EQ-CR-03",
    name: "Débosseleur tôlerie - 1/2",
    workshop: "Carrosserie",
    status: "Opérationnel",
    purchaseDate: "2023-10-14",
    warrantyEnd: "2025-10-14",
    purchasePrice: 3400,
    location: "Poste de tôlerie active",
    serialNumber: "DEB-CR-01",
    critical: true,
    mtbfTargetHours: 900,
    mttrTargetHours: 2
  },
  {
    code: "EQ-CR-04",
    name: "Débosseleur tôlerie - 2/2",
    workshop: "Carrosserie",
    status: "Hors Service",
    purchaseDate: "2023-10-14",
    warrantyEnd: "2025-10-14",
    purchasePrice: 3400,
    location: "Poste de tôlerie active",
    serialNumber: "DEB-CR-02",
    critical: true,
    mtbfTargetHours: 900,
    mttrTargetHours: 2
  },
  {
    code: "EQ-CR-05",
    name: "Presse de carrossier hydraulique",
    workshop: "Carrosserie",
    status: "Dégradé",
    purchaseDate: "2022-06-20",
    warrantyEnd: "2024-06-20",
    purchasePrice: 2800,
    location: "Poste d'ajustement structurel",
    serialNumber: "PRS-CR-05",
    critical: true,
    mtbfTargetHours: 1200,
    mttrTargetHours: 3
  },
  {
    code: "EQ-CR-06",
    name: "Sécheur infrarouge mobile - 1/2",
    workshop: "Carrosserie",
    status: "Hors Service",
    purchaseDate: "2023-02-15",
    warrantyEnd: "2025-02-15",
    purchasePrice: 1950,
    location: "Zone séchage rapide peinture",
    serialNumber: "INF-DRY-01",
    critical: false,
    mtbfTargetHours: 800,
    mttrTargetHours: 2
  },
  {
    code: "EQ-CR-07",
    name: "Sécheur infrarouge mobile - 2/2",
    workshop: "Carrosserie",
    status: "Hors Service",
    purchaseDate: "2023-02-15",
    warrantyEnd: "2025-02-15",
    purchasePrice: 1950,
    location: "Zone séchage rapide peinture",
    serialNumber: "INF-DRY-02",
    critical: false,
    mtbfTargetHours: 800,
    mttrTargetHours: 2
  },
  {
    code: "EQ-CR-08",
    name: "Chignole (Perceuse) pneumatique",
    workshop: "Carrosserie",
    status: "Dégradé",
    purchaseDate: "2024-01-20",
    warrantyEnd: "2025-01-20",
    purchasePrice: 310,
    location: "Postes de tôlerie",
    serialNumber: "CHG-PNEU-08",
    critical: false,
    mtbfTargetHours: 700,
    mttrTargetHours: 1
  },
  {
    code: "EQ-CR-09",
    name: "Meuleuse à disque",
    workshop: "Carrosserie",
    status: "Opérationnel",
    purchaseDate: "2024-01-25",
    warrantyEnd: "2025-01-25",
    purchasePrice: 240,
    location: "Postes de découpe tôles",
    serialNumber: "MUL-DISQ-09",
    critical: false,
    mtbfTargetHours: 800,
    mttrTargetHours: 1
  },
  {
    code: "EQ-CR-10",
    name: "Pistolet d'air chaud - 1/2",
    workshop: "Carrosserie",
    status: "Opérationnel",
    purchaseDate: "2023-04-10",
    warrantyEnd: "2025-04-10",
    purchasePrice: 180,
    location: "Atelier plastiques / Pare-chocs",
    serialNumber: "PST-CH-01",
    critical: true,
    mtbfTargetHours: 1000,
    mttrTargetHours: 1
  },
  {
    code: "EQ-CR-11",
    name: "Pistolet d'air chaud - 2/2",
    workshop: "Carrosserie",
    status: "Hors Service",
    purchaseDate: "2023-04-10",
    warrantyEnd: "2025-04-10",
    purchasePrice: 180,
    location: "Atelier plastiques / Pare-chocs",
    serialNumber: "PST-CH-02",
    critical: true,
    mtbfTargetHours: 1000,
    mttrTargetHours: 1
  },
  {
    code: "EQ-CR-12",
    name: "Servante d'atelier Carrosserie - 1/3",
    workshop: "Carrosserie",
    status: "Dégradé",
    purchaseDate: "2022-07-15",
    warrantyEnd: "2024-07-15",
    purchasePrice: 2100,
    location: "Zone de tôlerie active",
    serialNumber: "SRV-CR-01",
    critical: true,
    mtbfTargetHours: 1500,
    mttrTargetHours: 1
  },
  {
    code: "EQ-CR-13",
    name: "Servante d'atelier Carrosserie - 2/3",
    workshop: "Carrosserie",
    status: "Dégradé",
    purchaseDate: "2022-07-15",
    warrantyEnd: "2024-07-15",
    purchasePrice: 2100,
    location: "Zone de tôlerie active",
    serialNumber: "SRV-CR-02",
    critical: true,
    mtbfTargetHours: 1500,
    mttrTargetHours: 1
  },
  {
    code: "EQ-CR-14",
    name: "Servante d'atelier Carrosserie - 3/3",
    workshop: "Carrosserie",
    status: "Dégradé",
    purchaseDate: "2022-07-15",
    warrantyEnd: "2024-07-15",
    purchasePrice: 2100,
    location: "Zone de tôlerie active",
    serialNumber: "SRV-CR-03",
    critical: true,
    mtbfTargetHours: 1500,
    mttrTargetHours: 1
  },
  {
    code: "EQ-CR-15",
    name: "Pistolet silicone manuel",
    workshop: "Carrosserie",
    status: "Dégradé",
    purchaseDate: "2024-01-05",
    warrantyEnd: "2025-01-05",
    purchasePrice: 85,
    location: "Zone collage pare-brise",
    serialNumber: "PST-SIL-15",
    critical: true,
    mtbfTargetHours: 800,
    mttrTargetHours: 1
  },
  {
    code: "EQ-CR-16",
    name: "Cabine de peinture Weinmann",
    workshop: "Carrosserie",
    status: "Opérationnel",
    purchaseDate: "2024-06-25",
    warrantyEnd: "2026-06-25",
    purchasePrice: 82000,
    location: "Zone Tôlerie/Peinture",
    serialNumber: "WM-CAB-STA-2026",
    critical: true,
    lastInspectionDate: "2026-06-28",
    inspectionIntervalMonths: 12,
    mtbfTargetHours: 1800,
    mttrTargetHours: 6
  },
  {
    code: "EQ-CR-17",
    name: "Compresseur à vis Carrosserie",
    workshop: "Carrosserie",
    status: "Opérationnel",
    purchaseDate: "2024-06-25",
    warrantyEnd: "2026-06-25",
    purchasePrice: 19500,
    location: "Local d'air Carrosserie",
    serialNumber: "ATC-COMP-CR",
    critical: true,
    lastInspectionDate: "2026-06-28",
    inspectionIntervalMonths: 6,
    mtbfTargetHours: 1500,
    mttrTargetHours: 4
  },
  {
    code: "EQ-CR-18",
    name: "Aspirateur de carrossier mobile",
    workshop: "Carrosserie",
    status: "Hors Service",
    purchaseDate: "2023-03-12",
    warrantyEnd: "2024-03-12",
    purchasePrice: 850,
    location: "Poste ponçage mastic",
    serialNumber: "ASP-CR-18",
    critical: false,
    mtbfTargetHours: 800,
    mttrTargetHours: 2
  },

  // --- Zone: Maintenance Bâtiment & Infrastructure ---
  {
    code: "EQ-BAT-ELEC",
    name: "Armoires Électriques TGBT & Distribution Bâtiment",
    workshop: "Maintenance Bâtiment",
    status: "Opérationnel",
    purchaseDate: "2020-01-15",
    warrantyEnd: "2025-01-15",
    purchasePrice: 45000,
    location: "Local Technique TGBT",
    serialNumber: "TGBT-STA-01",
    critical: true,
    mtbfTargetHours: 2500,
    mttrTargetHours: 3
  },
  {
    code: "EQ-BAT-CLIM",
    name: "Système de Climatisation & VRV (Showroom & Bureaux)",
    workshop: "Maintenance Bâtiment",
    status: "Opérationnel",
    purchaseDate: "2021-05-10",
    warrantyEnd: "2026-05-10",
    purchasePrice: 65000,
    location: "Toiture & Locaux Climatisation",
    serialNumber: "VRV-CLIM-STA",
    critical: true,
    mtbfTargetHours: 2000,
    mttrTargetHours: 4
  },
  {
    code: "EQ-BAT-PLOMB",
    name: "Réseau de Plomberie, Sanitaires & Pompe Surpresseur",
    workshop: "Maintenance Bâtiment",
    status: "Opérationnel",
    purchaseDate: "2020-01-15",
    warrantyEnd: "2025-01-15",
    purchasePrice: 18000,
    location: "Bâtiment Principal & Sanitaires",
    serialNumber: "PLOMB-STA-01",
    critical: true,
    mtbfTargetHours: 3000,
    mttrTargetHours: 2
  },
  {
    code: "EQ-BAT-SERR",
    name: "Portes Automatiques, Rideaux Métalliques & Serrurerie",
    workshop: "Maintenance Bâtiment",
    status: "Opérationnel",
    purchaseDate: "2022-03-20",
    warrantyEnd: "2025-03-20",
    purchasePrice: 22000,
    location: "Accès Ateliers & Showroom",
    serialNumber: "SERR-STA-01",
    critical: true,
    mtbfTargetHours: 2000,
    mttrTargetHours: 3
  },
  {
    code: "EQ-BAT-ECLAIR",
    name: "Éclairage LED & Projecteurs Ateliers / Extérieur",
    workshop: "Maintenance Bâtiment",
    status: "Opérationnel",
    purchaseDate: "2023-01-10",
    warrantyEnd: "2026-01-10",
    purchasePrice: 12000,
    location: "Ateliers & Abords STA Chery",
    serialNumber: "LED-STA-01",
    critical: false,
    mtbfTargetHours: 4000,
    mttrTargetHours: 2
  }
];

export const INITIAL_SPARE_PARTS: SparePart[] = [
  // === NEW OUTILLAGE & EQUIPMENTS REGISTERED AS DEMANDS (SPARE PARTS WITH STOCK 0) ===
  {
    code: "EQ-REQ-01",
    name: "Poignée de distribution d'huile (Gartec NE3206)",
    currentStock: 0,
    reorderPoint: 2,
    unitPrice: 350,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-SR-03", "EQ-SR-04"]
  },
  {
    code: "EQ-REQ-02",
    name: "Flexible d'air comprimé renforcé 10m",
    currentStock: 0,
    reorderPoint: 3,
    unitPrice: 120,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-SR-09"]
  },
  {
    code: "EQ-REQ-03",
    name: "Récupérateur d'huile par aspiration pneumatique",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 1200,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-SR-10", "EQ-SR-11", "EQ-SR-12", "EQ-SR-13"]
  },
  {
    code: "EQ-REQ-04",
    name: "Clé à choc professionnelle haute performance",
    currentStock: 0,
    reorderPoint: 4,
    unitPrice: 480,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-SR-14"]
  },
  {
    code: "EQ-REQ-05",
    name: "Cale en plastique de protection pont (Gomme)",
    currentStock: 0,
    reorderPoint: 16,
    unitPrice: 45,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-SR-15", "EQ-SR-16"]
  },
  {
    code: "EQ-REQ-06",
    name: "Miroir d'inspection télescopique sous châssis",
    currentStock: 0,
    reorderPoint: 2,
    unitPrice: 150,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-SR-17", "EQ-SR-18"]
  },
  {
    code: "EQ-REQ-07",
    name: "Table de travail d'atelier (Établi métallique lourd)",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 950,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: []
  },
  {
    code: "EQ-REQ-08",
    name: "Servante d'atelier complète 7 tiroirs garnie",
    currentStock: 0,
    reorderPoint: 2,
    unitPrice: 2200,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-AM-36", "EQ-AM-37", "EQ-CR-12", "EQ-CR-13", "EQ-CR-14"]
  },
  {
    code: "EQ-REQ-09",
    name: "Pistolet d'air comprimé ergonomique",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 65,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: []
  },
  {
    code: "EQ-REQ-10",
    name: "Bassin de récupération d'huile usée grande capacité",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 1800,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: []
  },
  {
    code: "EQ-REQ-11",
    name: "Kit d'accessoires de protection jantes (Démonte-pneu)",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 180,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-AM-05"]
  },
  {
    code: "EQ-REQ-12",
    name: "Imprimante thermique pour testeur de freinage",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 450,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-AM-06"]
  },
  {
    code: "EQ-REQ-13",
    name: "Flexible de rechange renforcé pour gonfleur",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 85,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-AM-08"]
  },
  {
    code: "EQ-REQ-14",
    name: "Enrouleur automatique d'air comprimé 15m",
    currentStock: 0,
    reorderPoint: 3,
    unitPrice: 380,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-AM-09"]
  },
  {
    code: "EQ-REQ-15",
    name: "Machine de rinçage de boîte de vitesse automatique",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 6800,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-AM-12"]
  },
  {
    code: "EQ-REQ-16",
    name: "Pont élévateur 2 colonnes Ravaglioli 4T",
    currentStock: 0,
    reorderPoint: 2,
    unitPrice: 15500,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-AM-13", "EQ-AM-14", "EQ-AM-15", "EQ-AM-16", "EQ-AM-17"]
  },
  {
    code: "EQ-REQ-17",
    name: "Étau de serrage d'établi Expert 150mm",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 290,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-AM-18", "EQ-AM-19"]
  },
  {
    code: "EQ-REQ-18",
    name: "Rallonge électrique industrielle sur enrouleur 25m",
    currentStock: 0,
    reorderPoint: 4,
    unitPrice: 140,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-AM-20", "EQ-AM-21"]
  },
  {
    code: "EQ-REQ-19",
    name: "Mélangeur de liquides industriels",
    currentStock: 0,
    reorderPoint: 2,
    unitPrice: 420,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-AM-22"]
  },
  {
    code: "EQ-REQ-20",
    name: "Arrache-amortisseur pneumatique d'atelier",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 1100,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-AM-23"]
  },
  {
    code: "EQ-REQ-21",
    name: "Presse hydraulique robuste 30 tonnes",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 4500,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-AM-25", "EQ-CR-05"]
  },
  {
    code: "EQ-REQ-22",
    name: "Support réglable de boîte de vitesse (Vérin de fosse)",
    currentStock: 0,
    reorderPoint: 3,
    unitPrice: 850,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-AM-26", "EQ-AM-27"]
  },
  {
    code: "EQ-REQ-23",
    name: "Support moteur universel d'atelier",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 680,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-AM-28"]
  },
  {
    code: "EQ-REQ-24",
    name: "Cric rouleur hydraulique d'atelier 3T",
    currentStock: 0,
    reorderPoint: 2,
    unitPrice: 720,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-AM-29"]
  },
  {
    code: "EQ-REQ-25",
    name: "Tapis roulant d'atelier / Chariot de visite",
    currentStock: 0,
    reorderPoint: 4,
    unitPrice: 190,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-AM-32"]
  },
  {
    code: "EQ-REQ-26",
    name: "Station de charge climatisation Konfort automatique",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 9800,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-AM-33", "EQ-AM-34"]
  },
  {
    code: "EQ-REQ-27",
    name: "Kit d'accessoires de redressage pour débosseleur",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 380,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-CR-03", "EQ-CR-04"]
  },
  {
    code: "EQ-REQ-28",
    name: "Chignole (Perceuse) pneumatique réversible carrossier",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 320,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-CR-08"]
  },
  {
    code: "EQ-REQ-29",
    name: "Meuleuse d'angle pneumatique à disque",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 260,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-CR-09"]
  },
  {
    code: "EQ-REQ-30",
    name: "Kit d'outillage démontage pare-brise Spider 3",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 1450,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: []
  },
  {
    code: "EQ-REQ-31",
    name: "Visseuse sans fil industrielle de carrossier",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 420,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: []
  },
  {
    code: "EQ-REQ-32",
    name: "Kit de clés plates (mousse thermoformée)",
    currentStock: 0,
    reorderPoint: 2,
    unitPrice: 280,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: []
  },
  {
    code: "EQ-REQ-33",
    name: "Kit de débosselage à froid sans peinture (DSP)",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 890,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: []
  },
  {
    code: "EQ-REQ-34",
    name: "Ponceuse pneumatique orbitale carrosserie",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 410,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: []
  },
  {
    code: "EQ-REQ-35",
    name: "Pistolet silicone pneumatique professionnel",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 340,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: ["EQ-CR-15"]
  },
  {
    code: "EQ-REQ-36",
    name: "Étagère métallique bureau Responsable Carrosserie",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 220,
    location: "Bureau Carrosserie",
    category: "Équipement & Outillage",
    compatibleEquipments: []
  },
  {
    code: "EQ-REQ-37",
    name: "Lustreuse pneumatique orbitale LHR15 MARK",
    currentStock: 0,
    reorderPoint: 1,
    unitPrice: 1250,
    location: "Magasin Outillage",
    category: "Équipement & Outillage",
    compatibleEquipments: []
  }
];

export const INITIAL_INTERVENTIONS: Intervention[] = [
  {
    id: "INT-2026-001",
    equipmentCode: "EQ-CR-16",
    type: "Préventif",
    title: "Entretien préventif Cabine de peinture",
    description: "Maintenance périodique, nettoyage complet des filtres d'extraction et contrôle d'étanchéité.",
    dateIntervention: "2026-06-27",
    durationHours: 8.0,
    costParts: 0,
    costLabor: 450,
    technician: "Technicien Spécialisé",
    status: "Terminé",
    partsUsed: [],
    notes: "Entretien fait le 27 et 28 Juin 2026"
  },
  {
    id: "INT-2026-002",
    equipmentCode: "EQ-CR-17",
    type: "Préventif",
    title: "Entretien préventif Compresseur à vis Carrosserie",
    description: "Vidange d'huile, changement des filtres et vérification de la pression d'alimentation d'air.",
    dateIntervention: "2026-06-27",
    durationHours: 4.0,
    costParts: 0,
    costLabor: 250,
    technician: "Technicien Interne",
    status: "Terminé",
    partsUsed: [],
    notes: "Entretien fait le 27 et 28 Juin 2026"
  }
];

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: "VND-APAVE",
    name: "Apave Tunisie",
    serviceType: "Organisme d'Inspection Réglementaire",
    phone: "+216 71 889 400",
    email: "contact@apave.com.tn",
    contactPerson: "Kamel Ben Amor",
    rating: 5
  },
  {
    id: "VND-SGS",
    name: "SGS Tunisie",
    serviceType: "Contrôles réglementaires et Étalonnage",
    phone: "+216 71 206 500",
    email: "tunis.control@sgs.com",
    contactPerson: "Monia Jendoubi",
    rating: 4
  },
  {
    id: "VND-SOCO",
    name: "Socomat SAS Tunisie",
    serviceType: "Fournisseur d'équipements de garage & SAV",
    phone: "+216 71 332 550",
    email: "sav@socomat.tn",
    contactPerson: "Walid Mansour",
    rating: 4
  },
  {
    id: "VND-TUNCOMP",
    name: "Tunisie Compresseurs",
    serviceType: "Spécialiste compresseurs & Réseaux d'air",
    phone: "+216 71 556 123",
    email: "technique@tuncomp.com",
    contactPerson: "Mohamed Ali Sassi",
    rating: 5
  },
  {
    id: "VND-AUTOEQUIP",
    name: "Automotive Equipment Engineering",
    serviceType: "Calibration d'appareils de diagnostic et géométrie",
    phone: "+216 71 668 991",
    email: "support@autoequip.tn",
    contactPerson: "Fares Gharbi",
    rating: 4
  }
];

export const INITIAL_CONTRACTS: MaintenanceContract[] = [
  {
    id: "CON-2026-01",
    title: "Contrat de maintenance préventive Cabine de Peinture",
    vendorId: "VND-SOCO",
    costAnnual: 4800,
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    status: "Actif",
    frequency: "Trimestriel",
    coveredEquipments: ["EQ-CR-16"]
  },
  {
    id: "CON-2026-02",
    title: "Contrat de maintenance préventive Compresseur d'air",
    vendorId: "VND-TUNCOMP",
    costAnnual: 2400,
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    status: "Actif",
    frequency: "Semestriel",
    coveredEquipments: ["EQ-CR-17"]
  },
  {
    id: "CON-2026-03",
    title: "Contrat d'inspection périodique obligatoire (Ponts élévateurs)",
    vendorId: "VND-APAVE",
    costAnnual: 1800,
    startDate: "2026-03-01",
    endDate: "2027-03-01",
    status: "Actif",
    frequency: "Semestriel",
    coveredEquipments: ["EQ-SR-05", "EQ-SR-06", "EQ-SR-07", "EQ-SR-08", "EQ-AM-13", "EQ-AM-14", "EQ-AM-15", "EQ-AM-16", "EQ-AM-17"]
  }
];

export const INITIAL_COMPLIANCE_CHECKS: ComplianceCheck[] = [
  {
    id: "CMP-2026-01",
    equipmentCode: "EQ-SR-05",
    title: "Contrôle d'épreuve de charge de pont élévateur",
    bodyName: "Apave Tunisie",
    inspectionDate: "2026-04-10",
    nextInspectionDate: "2026-10-10",
    status: "Conforme",
    reportRef: "AP-PV-9921/2026"
  },
  {
    id: "CMP-2026-02",
    equipmentCode: "EQ-AM-13",
    title: "Contrôle électrique et organes de sécurité de pont",
    bodyName: "Apave Tunisie",
    inspectionDate: "2026-04-10",
    nextInspectionDate: "2026-10-10",
    status: "Conforme",
    reportRef: "AP-PV-9922/2026"
  },
  {
    id: "CMP-2026-03",
    equipmentCode: "EQ-CR-16",
    title: "Contrôle réglementaire des rejets et ventilation cabine",
    bodyName: "SGS Tunisie",
    inspectionDate: "2026-06-28",
    nextInspectionDate: "2027-06-28",
    status: "Conforme",
    reportRef: "SGS-ENV-2026/01"
  }
];

export const BUDGET_2026: BudgetYear = {
  year: 2026,
  totalBudget: 150000,
  allocatedByWorkshop: {
    "Service Rapide": 25000,
    "Atelier Mécanique": 45000,
    "Atelier Diagnostic": 15000,
    "Carrosserie": 40000,
    "Lavage": 10000,
    "Réception Après-Vente": 5000,
    "Magasin Pièces de Rechange": 5000,
    "Maintenance Bâtiment": 10000
  },
  spentByWorkshop: {
    "Service Rapide": 6250,
    "Atelier Mécanique": 4120,
    "Atelier Diagnostic": 1120,
    "Carrosserie": 18450,
    "Lavage": 2220,
    "Réception Après-Vente": 1450,
    "Magasin Pièces de Rechange": 680,
    "Maintenance Bâtiment": 5960
  }
};

export const INITIAL_PURCHASE_REQUESTS: PurchaseRequest[] = [
  {
    id: "DA-2026-001",
    equipmentName: "Pont élévateur 2 colonnes Ravaglioli 4T",
    needReason: "Remplacement du pont hydraulique principal tombé en panne structurelle irréparable",
    urgency: "Critique",
    quantity: 1,
    vendorId: "VND-SOCO",
    requestedBy: "Atelier Mécanique / Elec",
    dateRequested: "2026-06-20",
    status: "Approuvé",
    estimatedCost: 15500
  },
  {
    id: "DA-2026-002",
    equipmentName: "Station de charge climatisation Konfort automatique",
    needReason: "Forte demande sur le service climatisation d'été, station additionnelle requise",
    urgency: "Moyenne",
    quantity: 1,
    vendorId: "VND-AUTOEQUIP",
    requestedBy: "Atelier Service Rapide",
    dateRequested: "2026-06-25",
    status: "Commandé",
    estimatedCost: 9800
  },
  {
    id: "DA-2026-003",
    equipmentName: "Nettoyeur haute pression eau chaude (Kärcher)",
    needReason: "Le nettoyeur actuel n'atteint plus la température requise pour le dégraissage châssis",
    urgency: "Critique",
    quantity: 1,
    vendorId: "VND-SOCO",
    requestedBy: "Atelier Lavage",
    dateRequested: "2026-07-01",
    status: "En attente",
    estimatedCost: 1800
  },
  {
    id: "DA-2026-004",
    equipmentName: "Machine de rinçage de boîte de vitesse automatique",
    needReason: "Lancement de la nouvelle prestation de vidange complète de BVA agréée par Chery",
    urgency: "Moyenne",
    quantity: 1,
    vendorId: "VND-SOCO",
    requestedBy: "Atelier Mécanique / Elec",
    dateRequested: "2026-07-02",
    status: "En attente",
    estimatedCost: 6800
  },
  {
    id: "DA-2026-005",
    equipmentName: "Servantes d'atelier 7 tiroirs équipées (Beta)",
    needReason: "Mise à niveau de l'outillage individuel des nouveaux techniciens recrutés",
    urgency: "Faible",
    quantity: 3,
    vendorId: "VND-SOCO",
    requestedBy: "Atelier Service Rapide",
    dateRequested: "2026-07-04",
    status: "En attente",
    estimatedCost: 6600
  },
  {
    id: "DA-2026-006",
    equipmentName: "Presse hydraulique robuste 30 tonnes",
    needReason: "Presse actuelle du pôle tolerie déformée et non sécuritaire pour les opérateurs",
    urgency: "Critique",
    quantity: 1,
    vendorId: "VND-SOCO",
    requestedBy: "Atelier Carrosserie",
    dateRequested: "2026-07-05",
    status: "En attente",
    estimatedCost: 4500
  },
  {
    id: "DA-2026-007",
    equipmentName: "Lustreuse pneumatique orbitale LHR15",
    needReason: "Amélioration de la productivité du pôle lustrage et finition de la peinture carrosserie",
    urgency: "Moyenne",
    quantity: 2,
    vendorId: "VND-AUTOEQUIP",
    requestedBy: "Atelier Carrosserie",
    dateRequested: "2026-07-06",
    status: "En attente",
    estimatedCost: 2500
  },
  {
    id: "DA-2026-008",
    equipmentName: "Kit de débosselage à froid sans peinture (DSP)",
    needReason: "Permettre d'effectuer les réparations rapides d'impacts de grêle sans peinture",
    urgency: "Faible",
    quantity: 1,
    vendorId: "VND-SOCO",
    requestedBy: "Atelier Carrosserie",
    dateRequested: "2026-07-07",
    status: "En attente",
    estimatedCost: 890
  },
  {
    id: "DA-2026-009",
    equipmentName: "Étau de serrage d'établi Expert 150mm",
    needReason: "Équipement de l'établi supplémentaire installé dans la zone diagnostic mécanique",
    urgency: "Faible",
    quantity: 1,
    vendorId: "VND-SOCO",
    requestedBy: "Atelier Diagnostic",
    dateRequested: "2026-07-08",
    status: "Reçu",
    estimatedCost: 290
  }
];
